services:
  foo:
    image: foo:latest
    build: .
    pull_policy: build # Do not try to download the image. Build image every time instead.
    container_name: foo
    hostname: foo
    #domainname: ${DOMAINNAME}
    init: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - foo=bar
    ports:
      - "12345:12345"
    links:
      - "bar:aliasforbar"
    depends_on:
      bar:
        condition: service_healthy
      baz:
        condition: service_started # default
    restart: always
    stop_grace_period: 1m
    healthcheck:
      # start_interval https://github.com/docker/compose/issues/10830
      test: "bash -c '</dev/tcp/localhost/1234' || exit 1"
      test: "mysqladmin --password=foo ping || exit 1"
      test: "curl -f -A 'Docker: Health-Check' http://127.0.0.1/ || exit 1"
      start_period: 40s # if service needs more than $interval to start
      interval: 30s
      timeout: 30s
      retries: 3

  bar:
    networks:
      mynetwork:
        ipv4_address: 192.168.255.10 # comment for auto assign IP address
    image: hello-world
    hostname: bar
    container_name: bar

networks:
  default: # Instead of, or as well as, specifying your own networks, you can also change the settings of the app-wide default network by defining an entry under networks named 'default'
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: "192.168.255.0/24"
