version: '3.8'
services:
  foo:
    build: .
    image: foo:latest
    container_name: foo
    hostname: foo
    #domainname: ${DOMAINNAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - foo=bar
    ports:
      - "123456:123456"
    links:
      - "bar:aliasforbar"
    depends_on:
      - bar
    restart: always
    stop_grace_period: 1m
#    healthcheck:
#      test: "bash -c '</dev/tcp/localhost/3306' || exit 1"
#      test: "curl -f -A 'Docker: Health-Check' http://127.0.0.1/ || exit 1"
#      start_period: 40s # if service needs more than $interval to start
#      interval: 30s     # default
#      timeout: 3s
#      retries: 1

  bar:
    image: hello-world
    hostname: bar
    container_name: bar
